### ISSUE TITLE
Roadmap and contributions?

### ISSUE THREAD

**Issue by tchoutri** [milmazz/hunter#1]
Hi! I would like to contribute to your library.
Do you have some kind of roadmap  I could follow about the features to implement? 

If you are on Slack / Discord / IRC we could a bit more about it ;)
Have a nice day!

**Comment by milmazz** [comment]
Hi! Thanks for reaching out! All contributions are more than welcome, [here](https://github.com/milmazz/hunter/blob/master/README.md#todo) you can find a to-do list, you can pick any task you want to do, just let me know in advance to avoid overlapping.

Have a nice day too!

**Comment by tchoutri** [comment]
Okay cool =) I'll be starting to work on registering an application =)

**Comment by milmazz** [comment]
@tchoutri Good catch! I already updated the to-do list and added some basic steps on how to contribute. Let me know what do you think.

I'll try to connect to IRC this weekend, I'm on a road trip :)

**Comment by tchoutri** [comment]
Thanks a lot! Then I'll take the `Getting who reblogged/favourited a status` item. =)
On a side note, may I ask you your timezone or your city? I'm living near Paris.

Le 14 avril 2017 17:14:51 GMT+02:00, Milton Mazzarri <notifications@github.com> a écrit :
>@tchoutri Good catch! I already updated the to-do list and added some
>basic steps on how to contribute. Let me know what do you think.
>
>I'll try to connect to IRC this weekend, I'm on a road trip :)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/milmazz/hunter/issues/1#issuecomment-294171616

Théophile Choutri

https://www.linkedin.com/in/tchoutri

**Comment by vhf** [comment]
Streaming API support is not on the roadmap, is it an oversight or is it intentional?

**Comment by milmazz** [comment]
@vhf It was an oversight on my part, could you please send a Pull Request adding that task and other ones you think I'm missing? Thanks!

**Comment by milmazz** [comment]
Fixed via 8733c5c and 9754cd5
