### ISSUE TITLE
Hunter.create_status fails

### ISSUE THREAD

**Issue by optikfluffel** [milmazz/hunter#14]
When doing [`Hunter.create_status(conn, status_text)`](https://github.com/milmazz/hunter/blob/master/lib/hunter.ex#L401) without any options, the default is `[]`. This gets passed to [`Hunter.Status.create_status/3`](https://github.com/milmazz/hunter/blob/master/lib/hunter/status.ex#L106), which makes this empty options list into an empty map. Then it gets passed on to [`Hunter.Api.HTTPClient.create_status/3`](https://github.com/milmazz/hunter/blob/master/lib/hunter/api/http_client.ex#L155) which tries to da a `Keyword.put(options, :status, status)` onto that empty map.

This then finally results in:

```
** (FunctionClauseError) no function clause matching in Keyword.put/3    
    
    The following arguments were given to Keyword.put/3:
    
        # 1
        %{}
    
        # 2
        :status
    
        # 3
        "foobar"
    
    Attempted function clauses (showing 1 out of 1):
    
        def put(keywords, key, value) when is_list(keywords) and is_atom(key)
    
    (elixir) lib/keyword.ex:577: Keyword.put/3
```

**Comment by milmazz** [comment]
@optikfluffel Hey, thanks for the report and the detail. It should be fixed now, please let me know what do you think.

**Comment by optikfluffel** [comment]
@milmazz yes, seems fine now, thanks again 😁
